<Gerenciador>:
    Menu:
        name: 'menu'
    Tarefas:
        name: 'tarefas'

<Menu>:
    BoxLayout:
        orientation: 'vertical'
        padding: 200
        spacing: 10
        Image:
            source: 'logo-kivy.png'
            size_hint_y: None
            height: 100
            allow_stretch: True # estica a imagem fora dos limites de sua resolução
        Button:
            text: 'Tarefas'
            on_release: app.root.current = 'tarefas'
        Button:
            text: 'Assistente'
        Button:
            text: 'Sair'
            on_release: app.stop()

<Tarefas>:
    BoxLayout:
        orientation: 'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title: 'Tarefas'
                    on_release: app.root.current= 'menu'
                ActionButton:
                    text: 'Sair'
                ActionSeparator:
                ActionButton:
                    text: 'Menu'
        ScrollView:
            BoxLayout:
                id: box
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
        BoxLayout:
            size_hint_y: None
            height: 60
            TextInput:
                id: texto
            Button:
                text: '+'
                size_hint_x: None
                width: 60
                on_release: root.addWidget()
    
<Tarefa>:
    size_hint_y: None
    height: 200
    Label:
        id: label
        font_size: 30
    Button:
        text:  'X'
        size_hint_x: None
        width: 60
        on_release: app.root.get_screen('tarefas').ids.box.remove_widget(self.parent)